version: '3'

services:
  pipelines:
    image: ghcr.io/open-webui/pipelines:latest
    ports:
      - '9099:9099'
    volumes:
      - ./pipelines-remote:/app/pipelines
    env_file:
      - .env
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - '3000:8080'
    volumes:
      - ./open-webui:/app/backend/data
    environment:
      - WEBUI_AUTH=False # Set to True to enable authentication
      - OPENAI_API_BASE_URL=http://host.docker.internal:9099 # URL for the pipelines service
      - OPENAI_API_KEY=0p3n-w3bu! # API key for the pipelines service (default)
    depends_on:
      - pipelines
